### ISSUE TITLE
KeyError: 'articleId'

### ISSUE THREAD

**Issue by yang-liguang** [Receiling/UniRE#7]
当我训练SciERC时，发生如下错误，有人遇到过吗？
[2021-12-30 12:30:40,742 - entity_relation_joint_decoder.py - line:274 - INFO]: Load bert tokenizer successfully.
Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\UniRE-master\entity_relation_joint_decoder.py", line 330, in <module>
    main()
  File "C:\Users\Administrator\Desktop\UniRE-master\entity_relation_joint_decoder.py", line 295, in main
    ace_dataset.build_dataset(vocab=vocab,
  File "C:\Users\Administrator\Desktop\UniRE-master\inputs\datasets\dataset.py", line 78, in build_dataset
    instance_settting['instance'].count_vocab_items(counter,
  File "C:\Users\Administrator\Desktop\UniRE-master\inputs\instance.py", line 61, in count_vocab_items
    field.count_vocab_items(counter, sentences)
  File "C:\Users\Administrator\Desktop\UniRE-master\inputs\fields\token_field.py", line 39, in count_vocab_items
    for sentence in sentences:
  File "C:\Users\Administrator\Desktop\UniRE-master\inputs\dataset_readers\ace_reader_for_joint_decoding.py", line 37, in __iter__
    state, results = self.get_tokens(line)
  File "C:\Users\Administrator\Desktop\UniRE-master\inputs\dataset_readers\ace_reader_for_joint_decoding.py", line 90, in get_tokens
    logger.error("article id: {} sentence id: {} doesn't contain 'sentText'.".format(line['articleId'], line['sentId']))
KeyError: 'articleId'

**Comment by Receiling** [comment]
这是由于输入数据中缺少了'articleId'这一项，可以检查一下输入数据，数据的预处理方式参照：https://github.com/Receiling/UniRE/tree/master/data
